apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartapp-deploy
  namespace: dev
  labels:
    app: cartapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartapp
  template:
    metadata:
      labels:
        app: cartapp
    spec:
      serviceAccountName: cartapp-sa
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: cartservice
          image: yakub363/cartservice:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7070
              protocol: TCP
          env:
            - name: REDIS_ADDR
              value: "redis:6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
          readinessProbe:
            grpc:
              port: 7070
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            grpc:
              port: 7070
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: dev
  labels:
    app: cartservice
spec:
  type: ClusterIP
  selector:
    app: cartapp
  ports:
    - name: grpc
      port: 7070
      targetPort: 7070
      protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartapp-sa
  namespace: dev

