apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: dev
data:
  init.sql: |
    CREATE DATABASE yakubdb;
    \c yakubdb;
    CREATE TABLE IF NOT EXISTS users (
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL,
      email TEXT UNIQUE NOT NULL
    );

