apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: dev
  labels:
    app: currencyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      serviceAccountName: currencyservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      containers:
        - name: currencyservice
          image: yakub363/currencyservice:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
              protocol: TCP
          env:
            - name: PORT
              value: "7000"
            - name: DISABLE_PROFILER
              value: "1"
          readinessProbe:
            grpc:
              port: 7000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            grpc:
              port: 7000
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            capabilities:
              drop:
                - ALL

---

apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: dev
  labels:
    app: currencyservice
spec:
  type: ClusterIP
  selector:
    app: currencyservice
  ports:
    - port: 7000
      targetPort: 7000
      protocol: TCP

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: currencyservice
  namespace: dev

