apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailapp-deploy
  namespace: dev
  labels:
    app: emailapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailapp
  template:
    metadata:
      labels:
        app: emailapp
    spec:
      serviceAccountName: emailapp-sa
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
      containers:
        - name: emailservice
          image: yakub363/emailservice:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: PORT
              value: "8080"
            - name: DISABLE_PROFILER
              value: "1"
          readinessProbe:
            grpc:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            grpc:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            capabilities:
              drop:
                - ALL

---

apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: dev
  labels:
    app: emailapp
spec:
  type: ClusterIP
  selector:
    app: emailservice
  ports:
    - port: 5000
      targetPort: 8080
      protocol: TCP

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: emailapp-sa
  namespace: dev

