apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: dev
type: Opaque
stringData:
  password: U3VwZXJTZWNyZXQxMjM=

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dev
type: Opaque
data:
  username: cG9zdGdyZXM=        
  password: cGFzc3dvcmQ=        

