apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-deploy
  namespace: dev
  labels:
    app: shippingapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingapp
  template:
    metadata:
      labels:
        app: shippingapp
    spec:
      serviceAccountName: shippingapp-sa
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: shippingservice
        image: yakub363/shippingservice:v1.0
        ports:
        - containerPort: 50051
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          grpc:
            port: 50051
          initialDelaySeconds: 10
          periodSeconds: 20
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: dev
  labels:
    app: shippingservice
spec:
  type: ClusterIP
  selector:
    app: shippingapp
  ports:
  - port: 50051
    targetPort: 50051
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shippingapp-sa
  namespace: dev

