apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-cart-chart.fullname" . }}-deploy
  namespace: {{ .Values.namespace }}
  labels:
    app: cartapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cartapp
  template:
    metadata:
      labels:
        app: cartapp
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: cartservice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
            - name: REDIS_ADDR
              value: {{ .Values.env.redisAddr | quote }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.redisPasswordSecret.name }}
                  key: {{ .Values.env.redisPasswordSecret.key }}
          readinessProbe:
            grpc:
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            grpc:
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            capabilities:
              drop:
                - ALL
