apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: cartservice
spec:
  type: {{ .Values.service.type }}
  selector:
    app: cartapp
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP

